import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from '@tanstack/react-router';
import { CarFrontIcon, HeartIcon, ListFilterIcon, PlusIcon, RefreshCwIcon, SparklesIcon, WalletIcon, } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, } from '@/components/ui/card';
import { EmptyState, Skeleton } from '@/components/ui/misc';
import { ListingCard } from '@/components/listing-card';
import { formatPrice, formatRelative } from '@/lib/format';
import { useFetchGroup, useFilterGroups, useListingStats, useListings } from '@/lib/queries';
export function DashboardPage() {
    const groups = useFilterGroups();
    const stats = useListingStats();
    const latest = useListings({ pageSize: 6, sort: 'newest' });
    const fetchGroup = useFetchGroup();
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "flex flex-wrap items-end justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-semibold", children: "Pulpit" }), _jsx("p", { className: "text-muted-foreground text-sm", children: "Przegl\u0105d Twoich grup filtr\u00F3w i naj\u015Bwie\u017Cszych ofert." })] }), _jsx(Button, { asChild: true, children: _jsxs(Link, { to: "/groups", children: [_jsx(PlusIcon, {}), "Zarz\u0105dzaj grupami"] }) })] }), _jsxs("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [_jsx(StatCard, { icon: _jsx(CarFrontIcon, {}), label: "Aktywne og\u0142oszenia", value: stats.data ? String(stats.data.active) : undefined }), _jsx(StatCard, { icon: _jsx(SparklesIcon, {}), label: "Nowe (24 h)", value: stats.data ? String(stats.data.fresh24h) : undefined }), _jsx(StatCard, { icon: _jsx(WalletIcon, {}), label: "\u015Arednia cena", value: stats.data ? formatPrice(stats.data.avgPrice) : undefined }), _jsx(StatCard, { icon: _jsx(HeartIcon, {}), label: "Ulubione", value: stats.data ? String(stats.data.favorites) : undefined })] }), _jsxs("section", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h2", { className: "text-lg font-semibold", children: "Grupy filtr\u00F3w" }), _jsx(Button, { asChild: true, variant: "ghost", size: "sm", children: _jsx(Link, { to: "/groups", children: "Wszystkie" }) })] }), groups.isLoading ? (_jsxs("div", { className: "grid gap-4 md:grid-cols-2", children: [_jsx(Skeleton, { className: "h-40" }), _jsx(Skeleton, { className: "h-40" })] })) : groups.data && groups.data.length > 0 ? (_jsx("div", { className: "grid gap-4 md:grid-cols-2", children: groups.data.map((group) => (_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { className: "min-w-0", children: [_jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx("span", { className: "size-2.5 shrink-0 rounded-full", style: { background: group.color ?? 'var(--primary)' } }), _jsx(Link, { to: "/groups/$groupId", params: { groupId: group.id }, className: "truncate hover:underline", children: group.name })] }), _jsx(CardDescription, { className: "truncate", children: group.description ?? 'Brak opisu' })] }), _jsxs(Button, { size: "sm", variant: "outline", disabled: fetchGroup.isPending, onClick: () => fetchGroup.mutate(group.id), children: [_jsx(RefreshCwIcon, { className: fetchGroup.isPending && fetchGroup.variables === group.id
                                                            ? 'animate-spin'
                                                            : undefined }), "Pobierz"] })] }) }), _jsxs(CardContent, { className: "pt-4", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2 text-sm", children: [_jsxs(Badge, { variant: "secondary", children: [group.filters.length, " filtr\u00F3w"] }), _jsxs(Badge, { variant: "outline", children: [group.listingCount, " ofert"] }), group.newListingCount > 0 ? (_jsxs(Badge, { variant: "success", children: ["+", group.newListingCount, " nowych"] })) : null, !group.isActive ? (_jsx(Badge, { variant: "outline", children: "Wstrzymana" })) : null] }), _jsxs("p", { className: "text-muted-foreground mt-3 text-xs", children: ["Ostatnie pobranie: ", formatRelative(group.lastFetchedAt), " \u00B7 co", ' ', group.refreshIntervalMinutes, " min"] })] })] }, group.id))) })) : (_jsx(EmptyState, { icon: _jsx(ListFilterIcon, { className: "size-8" }), title: "Nie masz jeszcze \u017Cadnej grupy filtr\u00F3w", description: "Grupa to zestaw wyszukiwa\u0144, np. Volvo + Toyota w jednej, a Mazda + Kia w drugiej.", action: _jsx(Button, { asChild: true, children: _jsxs(Link, { to: "/groups", children: [_jsx(PlusIcon, {}), "Utw\u00F3rz pierwsz\u0105 grup\u0119"] }) }) }))] }), _jsxs("section", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h2", { className: "text-lg font-semibold", children: "Najnowsze oferty" }), _jsx(Button, { asChild: true, variant: "ghost", size: "sm", children: _jsx(Link, { to: "/listings", children: "Wszystkie og\u0142oszenia" }) })] }), latest.isLoading ? (_jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-3", children: Array.from({ length: 3 }).map((_, i) => (_jsx(Skeleton, { className: "h-72" }, i))) })) : latest.data && latest.data.items.length > 0 ? (_jsx("div", { className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-3", children: latest.data.items.map((listing) => (_jsx(ListingCard, { listing: listing }, listing.id))) })) : (_jsx(EmptyState, { icon: _jsx(CarFrontIcon, { className: "size-8" }), title: "Brak ofert", description: "Uruchom pobieranie w jednej z grup filtr\u00F3w, aby zobaczy\u0107 wyniki." }))] })] }));
}
function StatCard({ icon, label, value, }) {
    return (_jsx(Card, { children: _jsxs(CardContent, { className: "flex items-center gap-4 py-5", children: [_jsx("span", { className: "bg-secondary text-secondary-foreground grid size-10 shrink-0 place-items-center rounded-lg [&>svg]:size-5", children: icon }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "text-muted-foreground text-xs", children: label }), value === undefined ? (_jsx(Skeleton, { className: "mt-1 h-6 w-20" })) : (_jsx("p", { className: "tabular truncate text-xl font-semibold", children: value }))] })] }) }));
}
