/**
 * Hand-curated starter content for the vehicle knowledge base - the part
 * that works with zero configuration, no scraping and no API key. Covers
 * some of the most common cars on the Polish market. Anything not listed
 * here can still be added later through the admin panel's "Generuj" action
 * (Anthropic API, optional - see ANTHROPIC_API_KEY in .env).
 *
 * Safe to re-run: `upsertModel` replaces a generation's engines/issues/notes
 * rather than piling up duplicates.
 */
import { logger } from '../config/logger.js';
import { pool } from '../db/client.js';
import { upsertModel, type ModelPayload } from '../modules/knowledge/knowledge.service.js';

const MODELS: ModelPayload[] = [
  {
    make: 'Volkswagen',
    model: 'Golf',
    generation: 'Mk7',
    yearFrom: 2012,
    yearTo: 2019,
    bodyTypes: ['hatchback', 'wagon'],
    summary:
      'Siódma generacja Golfa - jeden z najpopularniejszych samochodów w Polsce. Solidne wykonanie, ' +
      'szeroka gama silników i wersji, dobrze znany serwisom niezależnym. Rozsądny wybór na pierwszy ' +
      'samochód i do codziennych dojazdów.',
    source: 'manual',
    engines: [
      {
        name: '1.6 TDI 105 KM',
        engineCode: 'CLHA/CXXB',
        fuelType: 'diesel',
        displacementCm3: 1598,
        powerHp: 105,
        torqueNm: 250,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.5,
        topSpeedKmh: 188,
        fuelConsumptionCombined: 4.1,
        yearFrom: 2012,
        yearTo: 2019,
      },
      {
        name: '2.0 TDI 150 KM',
        engineCode: 'CRBC/DFGA',
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 150,
        torqueNm: 340,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.6,
        topSpeedKmh: 216,
        fuelConsumptionCombined: 4.4,
        yearFrom: 2012,
        yearTo: 2019,
      },
      {
        name: '1.4 TSI 125 KM',
        engineCode: 'CZDA',
        fuelType: 'petrol',
        displacementCm3: 1395,
        powerHp: 125,
        torqueNm: 200,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.3,
        topSpeedKmh: 200,
        fuelConsumptionCombined: 5.3,
        yearFrom: 2012,
        yearTo: 2019,
      },
    ],
    knownIssues: [
      {
        title: 'Osadzanie sadzy w EGR i DPF (TDI)',
        description:
          'Krótkie trasy miejskie sprzyjają zapychaniu filtra cząstek stałych i zaworu EGR w silnikach ' +
          'diesla - objawia się spadkiem mocy i trybem awaryjnym.',
        severity: 'moderate',
        mileageHint: 'zwykle po 100-150 tys. km przy jeździe miejskiej',
        engineName: '2.0 TDI 150 KM',
      },
      {
        title: 'Rozciąganie łańcucha rozrządu (TSI)',
        description:
          'Wczesne egzemplarze 1.4 TSI miały problemy z napinaczem i rozciąganiem łańcucha - ' +
          'w skrajnych przypadkach kończyło się to jego zerwaniem.',
        severity: 'serious',
        mileageHint: 'ryzyko rośnie po 100 tys. km bez wymiany napinacza',
        engineName: '1.4 TSI 125 KM',
      },
      {
        title: 'Elektryczna pompa wspomagania kierownicy',
        description: 'Awarie modułu elektrycznej pompy wspomagania - objawia się ciężką kierownicą.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Koroda progów i krawędzi drzwi',
        description: 'Roczniki 2012-2014 potrafią korodować na progach i dolnych krawędziach drzwi.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body:
          'Bardzo dobrze oceniany przez właścicieli - solidne wykonanie wnętrza, przewidywalne ' +
          'prowadzenie. Silniki TDI cenione za niskie spalanie w trasie.',
      },
      {
        kind: 'ownership_cost',
        body:
          'Serwis tańszy niż u konkurencji premium, części dostępne zamiennikowo. DSG wymaga wymiany ' +
          'oleju co ok. 60 tys. km, co część serwisów pomija.',
      },
      {
        kind: 'buying_advice',
        body:
          'Sprawdź historię serwisową łańcucha rozrządu w TSI i szczelność DPF w TDI. Unikaj ' +
          'egzemplarzy z bardzo krótkimi, miejskimi przebiegami rocznymi przy silnikach diesla.',
      },
    ],
  },
  {
    make: 'Skoda',
    model: 'Octavia',
    generation: 'III',
    yearFrom: 2013,
    yearTo: 2020,
    bodyTypes: ['hatchback', 'wagon'],
    summary:
      'Trzecia generacja Octavii - jeden z najczęściej wybieranych samochodów rodzinnych w Polsce. ' +
      'Duże wnętrze i bagażnik, ta sama płyta MQB co Golf VII, niższa cena przy podobnej jakości.',
    source: 'manual',
    engines: [
      {
        name: '2.0 TDI 150 KM',
        engineCode: 'CRBC',
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 150,
        torqueNm: 340,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.3,
        topSpeedKmh: 220,
        fuelConsumptionCombined: 4.3,
        yearFrom: 2013,
        yearTo: 2020,
      },
      {
        name: '1.6 TDI 105 KM',
        engineCode: 'CXXB',
        fuelType: 'diesel',
        displacementCm3: 1598,
        powerHp: 105,
        torqueNm: 250,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.9,
        topSpeedKmh: 190,
        fuelConsumptionCombined: 4.0,
        yearFrom: 2013,
        yearTo: 2020,
      },
      {
        name: '1.4 TSI 150 KM',
        engineCode: 'CZDA/CHPA',
        fuelType: 'petrol',
        displacementCm3: 1395,
        powerHp: 150,
        torqueNm: 250,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.1,
        topSpeedKmh: 215,
        fuelConsumptionCombined: 5.6,
        yearFrom: 2013,
        yearTo: 2020,
      },
    ],
    knownIssues: [
      {
        title: 'Zapychanie DPF i EGR przy jeździe miejskiej',
        description:
          'Tak jak w innych diesli grupy VAG - krótkie dystanse prowadzą do zapychania filtra cząstek ' +
          'stałych.',
        severity: 'moderate',
        mileageHint: 'po 100-150 tys. km przy jeździe miejskiej',
        engineName: null,
      },
      {
        title: 'Łańcuch rozrządu w silnikach TSI',
        description: 'Podobnie jak w Golfie VII - wczesne 1.4 TSI wymagały poprawionego napinacza łańcucha.',
        severity: 'serious',
        mileageHint: null,
        engineName: '1.4 TSI 150 KM',
      },
      {
        title: 'Sprzęgło dwumasowe (diesle)',
        description: 'Koło dwumasowe w wersjach z manualną skrzynią zużywa się szybciej przy agresywnej jeździe.',
        severity: 'moderate',
        mileageHint: 'zwykle 150-200 tys. km',
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Ceniona za przestronność i praktyczność, szczególnie w wersji kombi. Uznawana za "tańszego Golfa".',
      },
      {
        kind: 'ownership_cost',
        body: 'Bardzo dobra dostępność części i niezależnych serwisów - jeden z tańszych w utrzymaniu modeli segmentu C w Polsce.',
      },
      {
        kind: 'buying_advice',
        body: 'Wersje z DSG sprawdź pod kątem historii wymian oleju w skrzyni. Kombi (Combi) trzyma wartość lepiej niż hatchback.',
      },
    ],
  },
  {
    make: 'Toyota',
    model: 'Corolla',
    generation: 'E210',
    yearFrom: 2019,
    yearTo: null,
    bodyTypes: ['hatchback', 'wagon', 'sedan'],
    summary:
      'Dwunasta generacja Corolli, w Europie sprzedawana głównie jako hybryda. Nowa platforma TNGA, ' +
      'wysoka jakość wykonania i bardzo dobra opinia o niezawodności napędu hybrydowego.',
    source: 'manual',
    engines: [
      {
        name: '1.8 Hybrid 122 KM',
        engineCode: '2ZR-FXE',
        fuelType: 'hybrid',
        displacementCm3: 1798,
        powerHp: 122,
        torqueNm: 142,
        gearbox: 'automatic',
        driveType: 'fwd',
        acceleration0To100: 10.9,
        topSpeedKmh: 180,
        fuelConsumptionCombined: 4.5,
        yearFrom: 2019,
        yearTo: null,
      },
      {
        name: '2.0 Hybrid 184 KM',
        engineCode: 'M20A-FXS',
        fuelType: 'hybrid',
        displacementCm3: 1987,
        powerHp: 184,
        torqueNm: 190,
        gearbox: 'automatic',
        driveType: 'fwd',
        acceleration0To100: 7.9,
        topSpeedKmh: 180,
        fuelConsumptionCombined: 4.9,
        yearFrom: 2019,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Pęknięcia lakieru na klapie bagażnika/progach (niektóre egzemplarze)',
        description: 'Pojedyncze zgłoszenia odprysków i słabszej powłoki lakierniczej na krawędziach.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Zużycie hamulców na przednich klockach',
        description: 'System hybrydowy z odzyskiem energii nierównomiernie obciąża hamulce - klocki czasem zapiekają się z rzadka używane.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo wysoko oceniana niezawodność napędu hybrydowego - Toyota ma tu wieloletnie doświadczenie z Prius/Auris.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niskie spalanie w mieście dzięki hybrydzie, ale serwis autoryzowany droższy niż niezależny warsztat VAG/PSA.',
      },
      {
        kind: 'buying_advice',
        body: 'Bateria hybrydowa ma długą żywotność (Toyota podaje szeroką gwarancję) - nie ma potrzeby unikać wysokich przebiegów z tego powodu.',
      },
    ],
  },
  {
    make: 'BMW',
    model: '3',
    generation: 'F30',
    yearFrom: 2012,
    yearTo: 2019,
    bodyTypes: ['sedan', 'wagon'],
    summary:
      'Szósta generacja BMW serii 3 (sedan/kombi Touring). Klasyczny wybór segmentu premium - napęd na ' +
      'tylną oś w większości wersji, szeroka gama silników od 2.0 do 3.0 l.',
    source: 'manual',
    engines: [
      {
        name: '320d 184 KM',
        engineCode: 'N47D20',
        fuelType: 'diesel',
        displacementCm3: 1995,
        powerHp: 184,
        torqueNm: 380,
        gearbox: 'manual',
        driveType: 'rwd',
        acceleration0To100: 7.5,
        topSpeedKmh: 233,
        fuelConsumptionCombined: 4.5,
        yearFrom: 2012,
        yearTo: 2015,
      },
      {
        name: '320d 190 KM (B47)',
        engineCode: 'B47D20',
        fuelType: 'diesel',
        displacementCm3: 1995,
        powerHp: 190,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 7.1,
        topSpeedKmh: 235,
        fuelConsumptionCombined: 4.2,
        yearFrom: 2015,
        yearTo: 2019,
      },
      {
        name: '320i 184 KM',
        engineCode: 'N20B20',
        fuelType: 'petrol',
        displacementCm3: 1997,
        powerHp: 184,
        torqueNm: 270,
        gearbox: 'manual',
        driveType: 'rwd',
        acceleration0To100: 7.3,
        topSpeedKmh: 235,
        fuelConsumptionCombined: 6.1,
        yearFrom: 2012,
        yearTo: 2015,
      },
    ],
    knownIssues: [
      {
        title: 'Łańcuch rozrządu silnika N47',
        description:
          'Znany, poważny problem N47 - rozciąganie i zrywanie łańcucha rozrządu, umiejscowionego od ' +
          'strony skrzyni biegów (trudny/drogi dostęp).',
        severity: 'serious',
        mileageHint: 'ryzyko rośnie po 120-150 tys. km bez wymiany',
        engineName: '320d 184 KM',
      },
      {
        title: 'Wtryskiwacze piezo (N47/N57)',
        description: 'Awarie wtryskiwaczy objawiające się nierówną pracą silnika i zwiększonym spalaniem.',
        severity: 'moderate',
        mileageHint: null,
        engineName: '320d 184 KM',
      },
      {
        title: 'Turbosprężarka (silniki wysokoprężne)',
        description: 'Zużycie łożysk turbiny przy zaniedbanych wymianach oleju.',
        severity: 'moderate',
        mileageHint: 'zwykle po 150 tys. km przy rzadkich wymianach oleju',
        engineName: null,
      },
      {
        title: 'Zawieszenie - tuleje wahaczy',
        description: 'Tuleje przednich wahaczy i drążki stabilizatora zużywają się szybciej niż w konkurencji.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Ceniona za prowadzenie i komfort, ale wcześniejsze silniki N47 (do ok. 2015) mają złą reputację przez łańcuch rozrządu.',
      },
      {
        kind: 'ownership_cost',
        body: 'Serwis droższy niż w segmencie C nie-premium, szczególnie części oryginalne BMW. Niezależne serwisy specjalizujące się w BMW obniżają koszty.',
      },
      {
        kind: 'buying_advice',
        body: 'W 320d sprawdź koniecznie historię wymiany łańcucha rozrządu i stan turbiny. Wersje po liftingu (B47, od 2015) mają poprawiony układ rozrządu.',
      },
    ],
  },
  {
    make: 'Audi',
    model: 'A4',
    generation: 'B9',
    yearFrom: 2015,
    yearTo: null,
    bodyTypes: ['sedan', 'wagon'],
    summary:
      'Piąta generacja Audi A4 na platformie MLB Evo, dzielonej z A5 i Q5. Nowocześniejsza niż ' +
      'poprzedniczka B8, z cyfrowym kokpitem Virtual Cockpit w wyższych wersjach.',
    source: 'manual',
    engines: [
      {
        name: '2.0 TDI 150 KM',
        engineCode: 'DETA',
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 150,
        torqueNm: 320,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.9,
        topSpeedKmh: 222,
        fuelConsumptionCombined: 4.2,
        yearFrom: 2015,
        yearTo: null,
      },
      {
        name: '2.0 TDI Quattro 190 KM',
        engineCode: 'DETD',
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 190,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 7.1,
        topSpeedKmh: 240,
        fuelConsumptionCombined: 4.8,
        yearFrom: 2015,
        yearTo: null,
      },
      {
        name: '2.0 TFSI 190 KM',
        engineCode: 'DKDA',
        fuelType: 'petrol',
        displacementCm3: 1984,
        powerHp: 190,
        torqueNm: 320,
        gearbox: 'automatic',
        driveType: 'fwd',
        acceleration0To100: 7.3,
        topSpeedKmh: 237,
        fuelConsumptionCombined: 5.9,
        yearFrom: 2015,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Zapychanie kolektora ssącego osadem oleju (TFSI)',
        description: 'Bezpośredni wtrysk benzyny sprzyja osadzaniu się nagaru na zaworach ssących - okresowo wymaga czyszczenia.',
        severity: 'moderate',
        mileageHint: 'po ok. 100 tys. km',
        engineName: '2.0 TFSI 190 KM',
      },
      {
        title: 'Łańcuch rozrządu TFSI',
        description: 'Rozciąganie łańcucha rozrządu w silnikach EA888 gen. 3 - rzadsze niż w starszych generacjach, ale się zdarza.',
        severity: 'moderate',
        mileageHint: null,
        engineName: '2.0 TFSI 190 KM',
      },
      {
        title: 'Awarie modułu Virtual Cockpit',
        description: 'Sporadyczne zawieszanie się lub restarty cyfrowego zestawu wskaźników w wersjach wyższych.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobrze oceniana jakość wnętrza i wyciszenie. Diesle 2.0 TDI uznawane za dojrzałe i oszczędne w trasie.',
      },
      {
        kind: 'ownership_cost',
        body: 'Koszty serwisu wyższe niż VW/Škoda mimo współdzielonej platformy - dealer Audi droższy, niezależne serwisy VAG obniżają koszt napraw.',
      },
      {
        kind: 'buying_advice',
        body: 'Quattro warto rozważyć przy większych przebiegach rocznych i jeździe zimą, ale podnosi koszt eksploatacji (spalanie, opony).',
      },
    ],
  },
  {
    make: 'Volvo',
    model: 'XC60',
    generation: 'II',
    yearFrom: 2017,
    yearTo: null,
    bodyTypes: ['suv'],
    summary:
      'Druga generacja XC60 na platformie SPA, dzielonej z XC90 i S90. Skandynawski design, bardzo ' +
      'wysoko oceniane systemy bezpieczeństwa, silniki wyłącznie z rodziny Drive-E (4-cylindrowe).',
    source: 'manual',
    engines: [
      {
        name: 'D4 190 KM',
        engineCode: 'D4204T',
        fuelType: 'diesel',
        displacementCm3: 1969,
        powerHp: 190,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'fwd',
        acceleration0To100: 8.8,
        topSpeedKmh: 210,
        fuelConsumptionCombined: 5.0,
        yearFrom: 2017,
        yearTo: null,
      },
      {
        name: 'B4 (mild hybrid) 197 KM',
        engineCode: 'B4204T44',
        fuelType: 'diesel',
        displacementCm3: 1969,
        powerHp: 197,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 8.1,
        topSpeedKmh: 210,
        fuelConsumptionCombined: 5.4,
        yearFrom: 2019,
        yearTo: null,
      },
      {
        name: 'T8 Twin Engine 390 KM',
        engineCode: 'B4204T43',
        fuelType: 'plugin_hybrid',
        displacementCm3: 1969,
        powerHp: 390,
        torqueNm: 640,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 5.3,
        topSpeedKmh: 230,
        fuelConsumptionCombined: 2.1,
        yearFrom: 2017,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Awarie systemu start-stop / akumulatora AGM',
        description: 'Słabszy akumulator AGM przy krótkich trasach potrafi nie utrzymać funkcji start-stop.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Osad w EGR/DPF przy jeździe miejskiej (D4)',
        description: 'Podobnie jak w innych nowoczesnych dieslach - krótkie trasy sprzyjają zapychaniu układu oczyszczania spalin.',
        severity: 'moderate',
        mileageHint: null,
        engineName: 'D4 190 KM',
      },
      {
        title: 'Bateria wysokonapięciowa w T8',
        description: 'Wysoki koszt ewentualnej wymiany baterii trakcyjnej po utracie gwarancji - element do sprawdzenia stanu przed zakupem.',
        severity: 'serious',
        mileageHint: 'poza okresem gwarancji (zwykle 8 lat)',
        engineName: 'T8 Twin Engine 390 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Wysokie noty za bezpieczeństwo i komfort. Wnętrze i systemy multimedialne oceniane bardzo dobrze.',
      },
      {
        kind: 'ownership_cost',
        body: 'Serwis w klasie premium - podobny koszt do BMW/Audi. T8 Twin Engine ma niższe podatki firmowe, ale wyższą cenę zakupu.',
      },
      {
        kind: 'buying_advice',
        body: 'Przy T8 koniecznie sprawdź kondycję baterii trakcyjnej i historię serwisową układu hybrydowego.',
      },
    ],
  },
  {
    make: 'Opel',
    model: 'Astra',
    generation: 'K',
    yearFrom: 2015,
    yearTo: 2021,
    bodyTypes: ['hatchback', 'wagon'],
    summary:
      'Piąta generacja Astry - wyraźnie lżejsza od poprzedniczki (do 200 kg), z nowymi silnikami ' +
      'downsizingowymi. Popularny, rozsądnie wyceniany wybór segmentu C.',
    source: 'manual',
    engines: [
      {
        name: '1.6 CDTI 136 KM',
        engineCode: 'B16DTH',
        fuelType: 'diesel',
        displacementCm3: 1598,
        powerHp: 136,
        torqueNm: 320,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.7,
        topSpeedKmh: 210,
        fuelConsumptionCombined: 3.9,
        yearFrom: 2015,
        yearTo: 2021,
      },
      {
        name: '1.4 Turbo 150 KM',
        engineCode: 'B14NET',
        fuelType: 'petrol',
        displacementCm3: 1399,
        powerHp: 150,
        torqueNm: 245,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.8,
        topSpeedKmh: 210,
        fuelConsumptionCombined: 5.7,
        yearFrom: 2015,
        yearTo: 2021,
      },
    ],
    knownIssues: [
      {
        title: 'Rozrząd w silnikach diesla CDTI (łańcuch)',
        description: 'Łańcuch rozrządu w niektórych wariantach CDTI wymaga uważnego serwisowania - hałas przy rozruchu bywa sygnałem ostrzegawczym.',
        severity: 'moderate',
        mileageHint: null,
        engineName: '1.6 CDTI 136 KM',
      },
      {
        title: 'Elektronika - moduły komfortu',
        description: 'Sporadyczne awarie modułów sterujących szybami/centralnym zamkiem.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Doceniana za komfort jazdy i dobre siedzenia (system AGR). Mniej prestiżowa niż Golf/Octavia, ale tańsza w zakupie.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niższe ceny części niż w grupie VAG, szeroka sieć niezależnych serwisów.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź historię serwisową rozrządu w CDTI - to główny punkt ryzyka w tej generacji.',
      },
    ],
  },
  {
    make: 'Mercedes-Benz',
    model: 'C-Class',
    generation: 'W204',
    yearFrom: 2007,
    yearTo: 2014,
    bodyTypes: ['sedan', 'wagon', 'coupe'],
    summary:
      'Klasa C w generacji W204 - popularny wybór wśród aut z segmentu premium na rynku wtórnym ze ' +
      'względu na przystępne ceny przy zachowaniu prestiżu marki.',
    source: 'manual',
    engines: [
      {
        name: 'C220 CDI 170 KM',
        engineCode: 'OM651',
        fuelType: 'diesel',
        displacementCm3: 2143,
        powerHp: 170,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 8.3,
        topSpeedKmh: 232,
        fuelConsumptionCombined: 5.3,
        yearFrom: 2011,
        yearTo: 2014,
      },
      {
        name: 'C200 CGI 184 KM',
        engineCode: 'M271',
        fuelType: 'petrol',
        displacementCm3: 1796,
        powerHp: 184,
        torqueNm: 270,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 7.7,
        topSpeedKmh: 236,
        fuelConsumptionCombined: 7.3,
        yearFrom: 2007,
        yearTo: 2014,
      },
    ],
    knownIssues: [
      {
        title: 'Korozja (roczniki 2007-2010)',
        description: 'Wczesne egzemplarze W204 słyną z problemów z korozją progów, nadkoli i podłogi bagażnika.',
        severity: 'serious',
        mileageHint: 'niezależnie od przebiegu, zależnie od rocznika i przechowywania',
        engineName: null,
      },
      {
        title: 'Rozciąganie łańcucha rozrządu (M271)',
        description: 'Silniki benzynowe M271 z kompresorem/turbo mają skłonność do rozciągania łańcucha rozrządu.',
        severity: 'serious',
        mileageHint: 'po 100-150 tys. km',
        engineName: 'C200 CGI 184 KM',
      },
      {
        title: 'Wtryskiwacze i turbina OM651',
        description: 'Silnik 2.2 CDI (OM651) narażony na awarie wtryskiwaczy i turbosprężarki przy zaniedbanym serwisie.',
        severity: 'moderate',
        mileageHint: null,
        engineName: 'C220 CDI 170 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Duży prestiż marki w przystępnej cenie na rynku wtórnym, ale reputacja jakości wykonania z tego okresu jest gorsza niż wcześniejszych Mercedesów.',
      },
      {
        kind: 'ownership_cost',
        body: 'Serwis potrafi być kosztowny przy zaniedbanych egzemplarzach - korozja i awarie M271/OM651 generują spore koszty napraw.',
      },
      {
        kind: 'buying_advice',
        body: 'Dokładnie obejrzeć podwozie i progi pod kątem korozji przed zakupem - to najczęstszy powód odrzucenia egzemplarza w tej generacji.',
      },
    ],
  },
  {
    make: 'Kia',
    model: 'Sportage',
    generation: 'QL',
    yearFrom: 2016,
    yearTo: 2021,
    bodyTypes: ['suv'],
    summary:
      'Czwarta generacja Sportage - popularny kompaktowy SUV, korzysta z 7-letniej gwarancji Kia, co ' +
      'czyni go atrakcyjnym wyborem na rynku wtórnym przy młodszych egzemplarzach.',
    source: 'manual',
    engines: [
      {
        name: '1.7 CRDi 141 KM',
        engineCode: 'D4FD',
        fuelType: 'diesel',
        displacementCm3: 1685,
        powerHp: 141,
        torqueNm: 340,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 11.4,
        topSpeedKmh: 180,
        fuelConsumptionCombined: 4.7,
        yearFrom: 2016,
        yearTo: 2018,
      },
      {
        name: '2.0 CRDi 185 KM',
        engineCode: 'D4HA',
        fuelType: 'diesel',
        displacementCm3: 1995,
        powerHp: 185,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 9.2,
        topSpeedKmh: 201,
        fuelConsumptionCombined: 6.2,
        yearFrom: 2016,
        yearTo: 2021,
      },
    ],
    knownIssues: [
      {
        title: 'Dwumasowe koło zamachowe',
        description: 'Zużywa się szybciej przy mieszanym stylu jazdy, szczególnie w wersjach manualnych.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Osad w układzie EGR/DPF',
        description: 'Typowe dla nowoczesnych dieslowskich SUV-ów przy krótkich trasach miejskich.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Dobra opinia o jakości wykonania jak na tę cenę, wspierana długą gwarancją producenta.',
      },
      {
        kind: 'ownership_cost',
        body: 'Relatywnie niski koszt serwisu, dobra dostępność części, konkurencyjne ceny u dealera.',
      },
      {
        kind: 'buying_advice',
        body: 'Warto sprawdzić czy gwarancja producenta nadal obowiązuje - znacząco obniża ryzyko zakupu.',
      },
    ],
  },
  {
    make: 'Mazda',
    model: '3',
    generation: 'BM/BN',
    yearFrom: 2013,
    yearTo: 2018,
    bodyTypes: ['hatchback', 'sedan'],
    summary:
      'Trzecia generacja Mazdy 3 z technologią SkyActiv - lżejsza konstrukcja, wysokosprężne silniki ' +
      'benzynowe bez turbodoładowania. Ceniona za osiągi i prowadzenie w segmencie C.',
    source: 'manual',
    engines: [
      {
        name: '2.0 SkyActiv-G 120 KM',
        engineCode: 'PE-VPS',
        fuelType: 'petrol',
        displacementCm3: 1998,
        powerHp: 120,
        torqueNm: 210,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.7,
        topSpeedKmh: 195,
        fuelConsumptionCombined: 5.8,
        yearFrom: 2013,
        yearTo: 2018,
      },
      {
        name: '1.5 SkyActiv-D 105 KM',
        engineCode: 'S5-VPTS',
        fuelType: 'diesel',
        displacementCm3: 1499,
        powerHp: 105,
        torqueNm: 270,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.9,
        topSpeedKmh: 187,
        fuelConsumptionCombined: 3.9,
        yearFrom: 2013,
        yearTo: 2018,
      },
    ],
    knownIssues: [
      {
        title: 'Korozja progów i krawędzi drzwi',
        description: 'Podobnie jak inne modele Mazdy z tego okresu, podatna na korozję w newralgicznych punktach.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'System Stop&Start - zużycie akumulatora',
        description: 'Częste, krótkie trasy przyspieszają zużycie akumulatora obsługującego system start-stop.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobrze oceniane osiągi i prowadzenie jak na segment C bez turbodoładowania w wersji benzynowej.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niższy koszt serwisu niż marki niemieckie, ale gorsza dostępność części zamiennych niż VAG w niektórych regionach.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź stan progów i nadkoli pod kątem korozji, szczególnie w egzemplarzach z północnej/wschodniej Polski.',
      },
    ],
  },
  {
    make: 'Renault',
    model: 'Megane',
    generation: 'III',
    yearFrom: 2008,
    yearTo: 2016,
    bodyTypes: ['hatchback', 'wagon', 'coupe'],
    summary:
      'Trzecia generacja Meganea - bardzo popularny model na polskim rynku wtórnym dzięki niskim cenom ' +
      'zakupu. Wygodne zawieszenie, ale mieszana reputacja elektryki.',
    source: 'manual',
    engines: [
      {
        name: '1.5 dCi 110 KM',
        engineCode: 'K9K',
        fuelType: 'diesel',
        displacementCm3: 1461,
        powerHp: 110,
        torqueNm: 240,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 11.3,
        topSpeedKmh: 187,
        fuelConsumptionCombined: 4.2,
        yearFrom: 2008,
        yearTo: 2016,
      },
      {
        name: '1.6 16V 110 KM',
        engineCode: 'K4M',
        fuelType: 'petrol',
        displacementCm3: 1598,
        powerHp: 110,
        torqueNm: 148,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 11.5,
        topSpeedKmh: 188,
        fuelConsumptionCombined: 6.9,
        yearFrom: 2008,
        yearTo: 2016,
      },
    ],
    knownIssues: [
      {
        title: 'Awarie elektryki (czujniki, moduły komfortu)',
        description: 'Powtarzający się temat w tej generacji - problemy z czujnikami parkowania, szybami, centralnym zamkiem.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Turbina i EGR (dCi)',
        description: 'Silnik 1.5 dCi, mimo ogólnej trwałości, wymaga regularnej wymiany oleju - zaniedbania prowadzą do awarii turbiny.',
        severity: 'moderate',
        mileageHint: 'przy przekraczaniu zalecanych interwałów wymiany oleju',
        engineName: '1.5 dCi 110 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Komfortowe zawieszenie i przyzwoita jakość jazdy, ale reputacja podkopana przez powtarzające się usterki elektryki.',
      },
      {
        kind: 'ownership_cost',
        body: 'Bardzo niskie ceny zakupu na rynku wtórnym, ale koszty napraw elektryki mogą to zniwelować.',
      },
      {
        kind: 'buying_advice',
        body: 'Przetestuj dokładnie wszystkie funkcje elektryczne (szyby, czujniki, oświetlenie) przed zakupem.',
      },
    ],
  },

  /* ---------------------------- new brands ---------------------------- */

  {
    make: 'Ford',
    model: 'Focus',
    generation: 'Mk3',
    yearFrom: 2011,
    yearTo: 2018,
    bodyTypes: ['hatchback', 'wagon'],
    summary:
      'Trzecia generacja Focusa - jeden z lepiej prowadzących się aut segmentu C, ceniony za osiągi ' +
      'silników EcoBoost i dynamiczne zawieszenie.',
    source: 'manual',
    engines: [
      {
        name: '1.6 TDCi 115 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1560,
        powerHp: 115,
        torqueNm: 270,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.8,
        topSpeedKmh: 190,
        fuelConsumptionCombined: 3.7,
        yearFrom: 2011,
        yearTo: 2018,
      },
      {
        name: '1.0 EcoBoost 125 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 999,
        powerHp: 125,
        torqueNm: 170,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 11.0,
        topSpeedKmh: 190,
        fuelConsumptionCombined: 4.9,
        yearFrom: 2012,
        yearTo: 2018,
      },
    ],
    knownIssues: [
      {
        title: 'Skrzynia Powershift (DCT)',
        description:
          'Problematyczna dwusprzęgłowa skrzynia automatyczna - szarpanie przy ruszaniu, awarie modułu ' +
          'mechatronicznego.',
        severity: 'serious',
        mileageHint: 'często poniżej 100 tys. km',
        engineName: null,
      },
      {
        title: 'Turbina 1.0 EcoBoost',
        description: 'Zdarzają się awarie turbosprężarki i pompy wody przy zaniedbanym serwisie.',
        severity: 'moderate',
        mileageHint: null,
        engineName: '1.0 EcoBoost 125 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobrze oceniane prowadzenie, jedno z lepiej jeżdżących aut w segmencie C.',
      },
      {
        kind: 'ownership_cost',
        body: 'Wersje z manualną skrzynią tanie w utrzymaniu; automat Powershift podnosi ryzyko kosztownej naprawy.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź czy skrzynia to Powershift (DCT) czy klasyczny automat - DCT wymaga szczególnej ostrożności.',
      },
    ],
  },
  {
    make: 'Hyundai',
    model: 'Tucson',
    generation: 'TL',
    yearFrom: 2015,
    yearTo: 2020,
    bodyTypes: ['suv'],
    summary:
      'Trzecia generacja Tucsona - popularny kompaktowy SUV wspierany długą gwarancją Hyundaia, dobra ' +
      'alternatywa dla Kia Sportage (ta sama płyta).',
    source: 'manual',
    engines: [
      {
        name: '1.7 CRDi 115 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1685,
        powerHp: 115,
        torqueNm: 280,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 12.3,
        topSpeedKmh: 172,
        fuelConsumptionCombined: 4.7,
        yearFrom: 2015,
        yearTo: 2018,
      },
      {
        name: '2.0 CRDi 185 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1995,
        powerHp: 185,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 9.5,
        topSpeedKmh: 201,
        fuelConsumptionCombined: 6.4,
        yearFrom: 2015,
        yearTo: 2020,
      },
    ],
    knownIssues: [
      {
        title: 'Dwumasowe koło zamachowe',
        description: 'Zużywa się szybciej w wersjach manualnych z silnikiem diesla.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Osad w EGR/DPF',
        description: 'Typowe dla nowoczesnych dieslowskich SUV-ów przy krótkich trasach miejskich.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Solidny, dobrze wyposażony SUV segmentu kompaktowego.',
      },
      {
        kind: 'ownership_cost',
        body: 'Konkurencyjne ceny serwisu u dealera, dobra dostępność części.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź czy gwarancja producenta nadal obowiązuje (do 5 lat) - obniża ryzyko kosztownych napraw.',
      },
    ],
  },
  {
    make: 'Peugeot',
    model: '308',
    generation: 'II',
    yearFrom: 2013,
    yearTo: 2021,
    bodyTypes: ['hatchback', 'wagon'],
    summary:
      'Druga generacja 308 - nowocześniejsza od poprzedniczki, z charakterystycznym małym kierownicą ' +
      'i wysoko osadzonymi zegarami (i-Cockpit).',
    source: 'manual',
    engines: [
      {
        name: '1.6 BlueHDi 120 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1560,
        powerHp: 120,
        torqueNm: 300,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.2,
        topSpeedKmh: 192,
        fuelConsumptionCombined: 3.6,
        yearFrom: 2013,
        yearTo: 2021,
      },
      {
        name: '1.2 PureTech 130 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1199,
        powerHp: 130,
        torqueNm: 230,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.4,
        topSpeedKmh: 195,
        fuelConsumptionCombined: 5.1,
        yearFrom: 2014,
        yearTo: 2021,
      },
    ],
    knownIssues: [
      {
        title: 'Rozciąganie łańcucha rozrządu (PureTech)',
        description:
          'Znany problem silników PureTech 1.2 - rozciąganie i zrywanie łańcucha rozrządu, czasem ' +
          'prowadzące do uszkodzenia silnika.',
        severity: 'serious',
        mileageHint: 'zdarza się przed 100 tys. km',
        engineName: '1.2 PureTech 130 KM',
      },
      {
        title: 'Osad w EGR/DPF (BlueHDi)',
        description: 'Zapychanie układu oczyszczania spalin przy jeździe miejskiej.',
        severity: 'moderate',
        mileageHint: null,
        engineName: '1.6 BlueHDi 120 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Ceniony za oszczędność silników BlueHDi i nowoczesne wnętrze, ale reputacja PureTech nadszarpnięta przez problemy z rozrządem.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niskie spalanie w wersjach diesla, ale ryzyko kosztownej naprawy silnika PureTech.',
      },
      {
        kind: 'buying_advice',
        body: 'W wersji PureTech koniecznie sprawdź historię serwisową łańcucha rozrządu - to główne ryzyko tego silnika.',
      },
    ],
  },
  {
    make: 'Nissan',
    model: 'Qashqai',
    generation: 'J11',
    yearFrom: 2013,
    yearTo: 2021,
    bodyTypes: ['suv'],
    summary:
      'Druga generacja Qashqaia - jeden z pionierów segmentu kompaktowych crossoverów, ceniony za ' +
      'praktyczność i dobrą widoczność z fotela kierowcy.',
    source: 'manual',
    engines: [
      {
        name: '1.5 dCi 110 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1461,
        powerHp: 110,
        torqueNm: 260,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 11.9,
        topSpeedKmh: 174,
        fuelConsumptionCombined: 3.8,
        yearFrom: 2013,
        yearTo: 2021,
      },
      {
        name: '1.3 DIG-T 140 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1332,
        powerHp: 140,
        torqueNm: 240,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.4,
        topSpeedKmh: 188,
        fuelConsumptionCombined: 5.3,
        yearFrom: 2018,
        yearTo: 2021,
      },
    ],
    knownIssues: [
      {
        title: 'Skrzynia CVT (Xtronic)',
        description: 'Bezstopniowa skrzynia CVT krytykowana za odczucia z jazdy i koszty ewentualnej naprawy.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Osad w EGR/DPF',
        description: 'Typowe dla dieslowskich wersji przy jeździe miejskiej.',
        severity: 'minor',
        mileageHint: null,
        engineName: '1.5 dCi 110 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Jeden z pionierów segmentu kompaktowych crossoverów, ceniony za praktyczność.',
      },
      {
        kind: 'ownership_cost',
        body: 'Umiarkowane koszty serwisu, choć skrzynia CVT w razie awarii bywa kosztowna w naprawie.',
      },
      {
        kind: 'buying_advice',
        body: 'Przy wersji z CVT sprawdź historię wymian oleju w skrzyni - zaniedbanie skraca jej żywotność.',
      },
    ],
  },
  {
    make: 'Seat',
    model: 'Leon',
    generation: 'III',
    yearFrom: 2012,
    yearTo: 2020,
    bodyTypes: ['hatchback', 'wagon'],
    summary:
      'Trzecia generacja Leona na platformie MQB, dzielonej z Golfem VII - podobna jakość i technika ' +
      'przy nieco bardziej sportowym charakterze i niższej cenie.',
    source: 'manual',
    engines: [
      {
        name: '2.0 TDI 150 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 150,
        torqueNm: 340,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.6,
        topSpeedKmh: 216,
        fuelConsumptionCombined: 4.2,
        yearFrom: 2012,
        yearTo: 2020,
      },
      {
        name: '1.4 TSI 150 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1395,
        powerHp: 150,
        torqueNm: 250,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.0,
        topSpeedKmh: 213,
        fuelConsumptionCombined: 5.4,
        yearFrom: 2012,
        yearTo: 2020,
      },
    ],
    knownIssues: [
      {
        title: 'Łańcuch rozrządu (TSI)',
        description: 'Podobnie jak w innych modelach VAG z tego okresu - rozciąganie łańcucha w silnikach TSI.',
        severity: 'moderate',
        mileageHint: null,
        engineName: '1.4 TSI 150 KM',
      },
      {
        title: 'Osad w EGR/DPF (TDI)',
        description: 'Zapychanie układu oczyszczania spalin przy jeździe miejskiej.',
        severity: 'moderate',
        mileageHint: null,
        engineName: '2.0 TDI 150 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Sportowy charakter jak na segment C, dobre prowadzenie dzięki platformie MQB dzielonej z Golfem.',
      },
      {
        kind: 'ownership_cost',
        body: 'Podobny koszt serwisu do Golfa/Octavii, dobra dostępność części w warsztatach VAG.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdzenia identyczne jak w Golfie VII - łańcuch rozrządu w TSI, DPF w TDI.',
      },
    ],
  },
  {
    make: 'Honda',
    model: 'Civic',
    generation: 'X',
    yearFrom: 2016,
    yearTo: 2021,
    bodyTypes: ['hatchback', 'sedan'],
    summary:
      'Dziesiąta generacja Civica - odważna stylistyka, bardzo dobra jakość wykonania jak na standardy ' +
      'Hondy, mniej popularna na polskim rynku niż konkurencja VAG.',
    source: 'manual',
    engines: [
      {
        name: '1.0 VTEC Turbo 129 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 988,
        powerHp: 129,
        torqueNm: 200,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.9,
        topSpeedKmh: 200,
        fuelConsumptionCombined: 5.4,
        yearFrom: 2016,
        yearTo: 2021,
      },
      {
        name: '1.6 i-DTEC 120 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1597,
        powerHp: 120,
        torqueNm: 300,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.5,
        topSpeedKmh: 200,
        fuelConsumptionCombined: 3.8,
        yearFrom: 2016,
        yearTo: 2018,
      },
    ],
    knownIssues: [
      {
        title: 'Rozcieńczanie oleju paliwem',
        description:
          'Silniki benzynowe z bezpośrednim wtryskiem (1.0/1.5 VTEC Turbo) przy jeździe wyłącznie ' +
          'miejskiej mogą rozcieńczać olej paliwem.',
        severity: 'moderate',
        mileageHint: 'głównie przy jeździe wyłącznie miejskiej',
        engineName: '1.0 VTEC Turbo 129 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobra jakość wykonania i niezawodność silnikowa jak na standardy Hondy.',
      },
      {
        kind: 'ownership_cost',
        body: 'Dobra trwałość, ale serwisy niezależne rzadziej specjalizują się w Hondach niż w VAG.',
      },
      {
        kind: 'buying_advice',
        body: 'Przy silniku benzynowym z bezpośrednim wtryskiem sprawdź poziom i jakość oleju.',
      },
    ],
  },
  {
    make: 'Fiat',
    model: 'Panda',
    generation: 'III',
    yearFrom: 2011,
    yearTo: null,
    bodyTypes: ['hatchback'],
    summary:
      'Trzecia generacja Pandy - popularne miejskie auto, tanie w zakupie i eksploatacji, skromne ' +
      'wyposażenie i osiągi.',
    source: 'manual',
    engines: [
      {
        name: '1.2 8V 69 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1242,
        powerHp: 69,
        torqueNm: 102,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 14.3,
        topSpeedKmh: 158,
        fuelConsumptionCombined: 5.2,
        yearFrom: 2011,
        yearTo: null,
      },
      {
        name: '0.9 TwinAir 85 KM',
        engineCode: null,
        fuelType: 'petrol_lpg',
        displacementCm3: 875,
        powerHp: 85,
        torqueNm: 145,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 11.2,
        topSpeedKmh: 165,
        fuelConsumptionCombined: 4.2,
        yearFrom: 2012,
        yearTo: 2018,
      },
    ],
    knownIssues: [
      {
        title: 'Awarie silnika TwinAir',
        description:
          'Dwucylindrowy TwinAir (łańcuch rozrządu, cewki zapłonowe) ma gorszą reputację trwałości niż ' +
          'klasyczny 1.2 8V.',
        severity: 'moderate',
        mileageHint: null,
        engineName: '0.9 TwinAir 85 KM',
      },
      {
        title: 'Uboga ochrona antykorozyjna',
        description: 'Nadwozie podatne na korozję szybciej niż konkurencja.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Popularne miejskie auto - tanie w zakupie, ale skromne wyposażenie i osiągi.',
      },
      {
        kind: 'ownership_cost',
        body: 'Bardzo niski koszt zakupu i eksploatacji w wersji 1.2 8V, tańsze ubezpieczenie.',
      },
      {
        kind: 'buying_advice',
        body: 'Wersja 1.2 8V uznawana za bardziej niezawodną niż TwinAir - prostsza konstrukcja.',
      },
    ],
  },
  {
    make: 'Suzuki',
    model: 'Vitara',
    generation: 'LY',
    yearFrom: 2015,
    yearTo: null,
    bodyTypes: ['suv'],
    summary:
      'Kompaktowy, zwrotny SUV ceniony za dobry napęd AllGrip 4x4 jak na tę klasę i niższą cenę niż ' +
      'konkurencja.',
    source: 'manual',
    engines: [
      {
        name: '1.6 DDiS 120 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1598,
        powerHp: 120,
        torqueNm: 320,
        gearbox: 'manual',
        driveType: 'awd',
        acceleration0To100: 11.5,
        topSpeedKmh: 175,
        fuelConsumptionCombined: 4.2,
        yearFrom: 2015,
        yearTo: 2018,
      },
      {
        name: '1.4 Boosterjet 140 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1373,
        powerHp: 140,
        torqueNm: 220,
        gearbox: 'manual',
        driveType: 'awd',
        acceleration0To100: 10.2,
        topSpeedKmh: 190,
        fuelConsumptionCombined: 5.9,
        yearFrom: 2016,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Osad w EGR/DPF',
        description: 'Zapychanie układu oczyszczania spalin przy jeździe miejskiej (DDiS).',
        severity: 'minor',
        mileageHint: null,
        engineName: '1.6 DDiS 120 KM',
      },
      {
        title: 'Mniejsza sieć serwisowa',
        description: 'Węższa niż u konkurencji, co może wydłużać czas oczekiwania na części.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Kompaktowy, zwrotny SUV ceniony za dobry napęd AllGrip 4x4 jak na tę klasę.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niższe ceny nowego auta niż konkurencja, ale rzadsza sieć serwisowa może wydłużać naprawy.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź dostępność części w Twoim regionie przed zakupem.',
      },
    ],
  },
  {
    make: 'Lexus',
    model: 'RX',
    generation: 'IV',
    yearFrom: 2015,
    yearTo: 2022,
    bodyTypes: ['suv'],
    summary:
      'Czwarta generacja Lexusa RX - jedna z najwyżej ocenianych pod względem niezawodności aut ' +
      'premium, głównie sprzedawana z napędem hybrydowym.',
    source: 'manual',
    engines: [
      {
        name: 'RX 450h 313 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 3456,
        powerHp: 313,
        torqueNm: 335,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 7.7,
        topSpeedKmh: 200,
        fuelConsumptionCombined: 5.5,
        yearFrom: 2015,
        yearTo: 2022,
      },
      {
        name: 'RX 200t 238 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1998,
        powerHp: 238,
        torqueNm: 350,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 7.3,
        topSpeedKmh: 210,
        fuelConsumptionCombined: 8.1,
        yearFrom: 2015,
        yearTo: 2019,
      },
    ],
    knownIssues: [
      {
        title: 'Sporadyczne usterki',
        description: 'Praktycznie brak poważnych, powtarzalnych usterek zgłaszanych masowo - typowe dla Lexusa.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Koszt części po kolizji',
        description: 'Wysoki koszt oryginalnych części blacharskich i elektroniki w razie kolizji.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Jedna z najwyżej ocenianych pod względem niezawodności aut premium - solidna reputacja napędu hybrydowego.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niższe spalanie od konkurencji premium dzięki hybrydzie, ale wyższa cena zakupu i części.',
      },
      {
        kind: 'buying_advice',
        body: 'Bardzo bezpieczny wybór na rynku wtórnym - główne ryzyko to cena zakupu, nie stan techniczny.',
      },
    ],
  },

  /* --------------------- more models, existing brands -------------------- */

  {
    make: 'Volkswagen',
    model: 'Passat',
    generation: 'B8',
    yearFrom: 2014,
    yearTo: 2023,
    bodyTypes: ['sedan', 'wagon'],
    summary:
      'Ósma generacja Passata - bardzo popularny wybór firmowy i rodzinny, ceniony za komfort na ' +
      'trasie i jakość wykonania wnętrza.',
    source: 'manual',
    engines: [
      {
        name: '2.0 TDI 150 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 150,
        torqueNm: 340,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.7,
        topSpeedKmh: 216,
        fuelConsumptionCombined: 4.4,
        yearFrom: 2014,
        yearTo: 2023,
      },
      {
        name: '2.0 TDI 190 KM 4Motion',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 190,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 7.9,
        topSpeedKmh: 233,
        fuelConsumptionCombined: 5.0,
        yearFrom: 2014,
        yearTo: 2023,
      },
      {
        name: '1.5 TSI 150 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1498,
        powerHp: 150,
        torqueNm: 250,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.4,
        topSpeedKmh: 219,
        fuelConsumptionCombined: 5.7,
        yearFrom: 2019,
        yearTo: 2023,
      },
    ],
    knownIssues: [
      {
        title: 'Osad w EGR/DPF',
        description: 'Zapychanie układu oczyszczania spalin przy jeździe miejskiej (TDI).',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Awarie pompy wtryskowej wysokiego ciśnienia',
        description: 'Sporadyczne awarie pompy w silnikach TDI, zwykle przy zaniedbanym serwisie paliwa.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobrze oceniana jakość wykonania i komfort na trasie, popularny wybór firmowy i rodzinny.',
      },
      {
        kind: 'ownership_cost',
        body: 'Wyższy koszt niż Golf/Octavia, ale nadal rozsądny jak na segment D.',
      },
      {
        kind: 'buying_advice',
        body: 'Wersje 4Motion (awd) droższe w eksploatacji - sprawdź czy rzeczywiście potrzebny napęd na 4 koła.',
      },
    ],
  },
  {
    make: 'Volkswagen',
    model: 'Tiguan',
    generation: 'II',
    yearFrom: 2016,
    yearTo: null,
    bodyTypes: ['suv'],
    summary:
      'Druga generacja Tiguana na platformie MQB - bardzo popularny SUV kompaktowy w Polsce, ceniony ' +
      'za jakość wnętrza i uniwersalność.',
    source: 'manual',
    engines: [
      {
        name: '2.0 TDI 150 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 150,
        torqueNm: 340,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.3,
        topSpeedKmh: 199,
        fuelConsumptionCombined: 5.1,
        yearFrom: 2016,
        yearTo: null,
      },
      {
        name: '2.0 TDI 190 KM 4Motion',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 190,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 7.7,
        topSpeedKmh: 213,
        fuelConsumptionCombined: 5.9,
        yearFrom: 2016,
        yearTo: null,
      },
      {
        name: '1.5 TSI 150 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1498,
        powerHp: 150,
        torqueNm: 250,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.2,
        topSpeedKmh: 202,
        fuelConsumptionCombined: 6.3,
        yearFrom: 2018,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Osad w EGR/DPF',
        description: 'Zapychanie układu oczyszczania spalin przy jeździe miejskiej (TDI).',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Awarie modułu DSG',
        description: 'Zaniedbana wymiana oleju w skrzyni DSG prowadzi do awarii mechatroniki.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo popularny SUV kompaktowy w Polsce, ceniony za jakość wnętrza i uniwersalność.',
      },
      {
        kind: 'ownership_cost',
        body: 'Koszt serwisu zbliżony do Passata, wersje 4Motion droższe w utrzymaniu.',
      },
      {
        kind: 'buying_advice',
        body: 'Przy DSG sprawdź historię wymiany oleju w skrzyni - zaniedbanie to główny powód awarii.',
      },
    ],
  },
  {
    make: 'Volkswagen',
    model: 'Polo',
    generation: 'VI',
    yearFrom: 2017,
    yearTo: null,
    bodyTypes: ['hatchback'],
    summary:
      'Szósta generacja Polo, wyraźnie większa i lepiej wykonana niż poprzedniczka - uznawana za ' +
      '"małego Golfa".',
    source: 'manual',
    engines: [
      {
        name: '1.0 TSI 95 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 999,
        powerHp: 95,
        torqueNm: 175,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.8,
        topSpeedKmh: 187,
        fuelConsumptionCombined: 4.9,
        yearFrom: 2017,
        yearTo: null,
      },
      {
        name: '1.0 TSI 115 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 999,
        powerHp: 115,
        torqueNm: 200,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.5,
        topSpeedKmh: 198,
        fuelConsumptionCombined: 5.0,
        yearFrom: 2017,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Osad na zaworach ssących',
        description: 'Typowe dla całej gamy silników TSI grupy VAG z bezpośrednim wtryskiem.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Drobne usterki elektryki wnętrza',
        description: 'Sporadyczne problemy z nagłośnieniem i czujnikami.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobrze oceniana jakość wykonania jak na segment B, uznawana za "małego Golfa".',
      },
      {
        kind: 'ownership_cost',
        body: 'Tani w utrzymaniu, niskie spalanie silników TSI, dobra wartość rynkowa.',
      },
      {
        kind: 'buying_advice',
        body: 'Solidny wybór na pierwszy samochód - mało punktów ryzyka w porównaniu do większych modeli VAG.',
      },
    ],
  },
  {
    make: 'Skoda',
    model: 'Fabia',
    generation: 'III',
    yearFrom: 2014,
    yearTo: 2021,
    bodyTypes: ['hatchback', 'wagon'],
    summary:
      'Trzecia generacja Fabii - popularne miejskie/kompaktowe auto, cenione za niski koszt eksploatacji ' +
      'i dobrą przestrzeń bagażową jak na segment B.',
    source: 'manual',
    engines: [
      {
        name: '1.0 MPI 60 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 999,
        powerHp: 60,
        torqueNm: 95,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 15.5,
        topSpeedKmh: 164,
        fuelConsumptionCombined: 4.8,
        yearFrom: 2014,
        yearTo: 2021,
      },
      {
        name: '1.2 TSI 110 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1197,
        powerHp: 110,
        torqueNm: 175,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.7,
        topSpeedKmh: 195,
        fuelConsumptionCombined: 5.0,
        yearFrom: 2014,
        yearTo: 2018,
      },
      {
        name: '1.4 TDI 90 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1422,
        powerHp: 90,
        torqueNm: 230,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 11.3,
        topSpeedKmh: 178,
        fuelConsumptionCombined: 3.8,
        yearFrom: 2014,
        yearTo: 2018,
      },
    ],
    knownIssues: [
      {
        title: 'Łańcuch rozrządu (niektóre TSI)',
        description: 'Podobnie jak inne małe silniki TSI grupy VAG z tego okresu.',
        severity: 'minor',
        mileageHint: null,
        engineName: '1.2 TSI 110 KM',
      },
      {
        title: 'Osad w EGR/DPF (TDI)',
        description: 'Zapychanie układu oczyszczania spalin przy jeździe miejskiej.',
        severity: 'minor',
        mileageHint: null,
        engineName: '1.4 TDI 90 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo popularne miejskie/kompaktowe auto, cenione za niski koszt eksploatacji i dobrą przestrzeń bagażową.',
      },
      {
        kind: 'ownership_cost',
        body: 'Jeden z tańszych w utrzymaniu modeli VAG - niskie ceny części, oszczędne silniki.',
      },
      {
        kind: 'buying_advice',
        body: 'Wersja 1.0 MPI (bez turbo) uznawana za najbardziej bezawaryjną, choć najsłabszą osiągowo.',
      },
    ],
  },
  {
    make: 'Skoda',
    model: 'Superb',
    generation: 'III',
    yearFrom: 2015,
    yearTo: null,
    bodyTypes: ['sedan', 'wagon'],
    summary:
      'Trzecia generacja Superba - bardzo pojemne wnętrze i bagażnik jak na segment D, ceniony przez ' +
      'kierowców pokonujących duże przebiegi.',
    source: 'manual',
    engines: [
      {
        name: '2.0 TDI 150 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 150,
        torqueNm: 340,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.9,
        topSpeedKmh: 220,
        fuelConsumptionCombined: 4.3,
        yearFrom: 2015,
        yearTo: null,
      },
      {
        name: '2.0 TDI 190 KM 4x4',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 190,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 7.7,
        topSpeedKmh: 235,
        fuelConsumptionCombined: 5.2,
        yearFrom: 2015,
        yearTo: null,
      },
      {
        name: '1.5 TSI 150 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1498,
        powerHp: 150,
        torqueNm: 250,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.4,
        topSpeedKmh: 224,
        fuelConsumptionCombined: 5.7,
        yearFrom: 2019,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Osad w EGR/DPF',
        description: 'Zapychanie układu oczyszczania spalin przy jeździe miejskiej (TDI).',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Awarie czujników i modułów komfortu',
        description: 'Nagłaśniane w wersjach z bogatym wyposażeniem elektronicznym (L&K).',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo pojemne wnętrze i bagażnik jak na segment D, ceniony przez kierowców pokonujących duże przebiegi.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niższy koszt utrzymania niż Passat mimo zbliżonej klasy, bardzo dobra wartość rynkowa.',
      },
      {
        kind: 'buying_advice',
        body: 'Wersje L&K (najbogatsze wyposażenie) sprawdź pod kątem sprawności wszystkich systemów elektronicznych.',
      },
    ],
  },
  {
    make: 'Toyota',
    model: 'RAV4',
    generation: 'V',
    yearFrom: 2018,
    yearTo: null,
    bodyTypes: ['suv'],
    summary:
      'Piąta generacja RAV4 - jeden z bardziej polecanych SUV-ów rodzinnych, bardzo wysoko oceniana ' +
      'niezawodność napędu hybrydowego.',
    source: 'manual',
    engines: [
      {
        name: '2.5 Hybrid 218 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 2487,
        powerHp: 218,
        torqueNm: 221,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 8.1,
        topSpeedKmh: 180,
        fuelConsumptionCombined: 5.5,
        yearFrom: 2018,
        yearTo: null,
      },
      {
        name: '2.0 Valvematic 173 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1987,
        powerHp: 173,
        torqueNm: 199,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.9,
        topSpeedKmh: 190,
        fuelConsumptionCombined: 7.0,
        yearFrom: 2018,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Jakość lakieru na krawędziach',
        description: 'Sporadyczne zgłoszenia słabszej powłoki lakierniczej na krawędziach nadwozia.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo wysoko oceniana niezawodność napędu hybrydowego, jeden z bardziej polecanych SUV-ów rodzinnych.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niskie spalanie w hybrydzie, wysoka wartość rezydualna na rynku wtórnym.',
      },
      {
        kind: 'buying_advice',
        body: 'Hybryda zdecydowanie bardziej opłacalna przy dużym rocznym przebiegu i jeździe miejskiej.',
      },
    ],
  },
  {
    make: 'BMW',
    model: 'X3',
    generation: 'G01',
    yearFrom: 2017,
    yearTo: null,
    bodyTypes: ['suv'],
    summary:
      'Trzecia generacja X3 - bardzo dobrze oceniane prowadzenie jak na SUV-a, typowe dla BMW ' +
      'pozycjonowanie sportowe w segmencie premium.',
    source: 'manual',
    engines: [
      {
        name: 'xDrive20d 190 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1995,
        powerHp: 190,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 8.0,
        topSpeedKmh: 213,
        fuelConsumptionCombined: 5.2,
        yearFrom: 2017,
        yearTo: null,
      },
      {
        name: 'xDrive30d 265 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 2993,
        powerHp: 265,
        torqueNm: 620,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 5.8,
        topSpeedKmh: 240,
        fuelConsumptionCombined: 6.0,
        yearFrom: 2017,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Zawieszenie pneumatyczne',
        description: 'Awarie opcjonalnego zawieszenia pneumatycznego - kosztowna naprawa w razie usterki.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Osad w EGR/DPF',
        description: 'Typowe dla dieslowskich SUV-ów przy jeździe miejskiej.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobrze oceniane prowadzenie jak na SUV-a, typowe dla BMW pozycjonowanie sportowe.',
      },
      {
        kind: 'ownership_cost',
        body: 'Wysoki koszt serwisu i części, typowy dla klasy premium.',
      },
      {
        kind: 'buying_advice',
        body: 'Unikaj opcjonalnego zawieszenia pneumatycznego jeśli zależy Ci na niższych kosztach eksploatacji.',
      },
    ],
  },
  {
    make: 'Audi',
    model: 'A3',
    generation: '8V',
    yearFrom: 2012,
    yearTo: 2020,
    bodyTypes: ['hatchback', 'sedan'],
    summary:
      'Trzecia generacja A3 na platformie MQB - bardzo dobra jakość wnętrza jak na segment premium-kompakt, ' +
      'ceniona za wyciszenie.',
    source: 'manual',
    engines: [
      {
        name: '2.0 TDI 150 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1968,
        powerHp: 150,
        torqueNm: 320,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.6,
        topSpeedKmh: 216,
        fuelConsumptionCombined: 4.1,
        yearFrom: 2012,
        yearTo: 2020,
      },
      {
        name: '1.4 TFSI 150 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1395,
        powerHp: 150,
        torqueNm: 250,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 8.2,
        topSpeedKmh: 216,
        fuelConsumptionCombined: 5.2,
        yearFrom: 2012,
        yearTo: 2020,
      },
    ],
    knownIssues: [
      {
        title: 'Zapychanie kolektora ssącego',
        description: 'Osad na zaworach ssących w silnikach TFSI z bezpośrednim wtryskiem.',
        severity: 'moderate',
        mileageHint: 'po ok. 100 tys. km',
        engineName: '1.4 TFSI 150 KM',
      },
      {
        title: 'Osad w EGR/DPF (TDI)',
        description: 'Zapychanie układu oczyszczania spalin przy jeździe miejskiej.',
        severity: 'moderate',
        mileageHint: null,
        engineName: '2.0 TDI 150 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobra jakość wnętrza jak na segment premium-kompakt, ceniona za wyciszenie.',
      },
      {
        kind: 'ownership_cost',
        body: 'Koszt zbliżony do Golfa VII (współdzielona platforma MQB), ale serwis dealerski Audi droższy.',
      },
      {
        kind: 'buying_advice',
        body: 'Te same punkty kontrolne co Golf VII/Leon III - łańcuch rozrządu TFSI, DPF w TDI.',
      },
    ],
  },
  {
    make: 'Volvo',
    model: 'XC40',
    generation: 'I',
    yearFrom: 2017,
    yearTo: null,
    bodyTypes: ['suv'],
    summary:
      'Pierwsza generacja XC40 - bardzo dobrze oceniana pod względem designu i bezpieczeństwa, ' +
      'popularny wybór wśród młodszych nabywców segmentu premium.',
    source: 'manual',
    engines: [
      {
        name: 'D4 190 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1969,
        powerHp: 190,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 7.9,
        topSpeedKmh: 205,
        fuelConsumptionCombined: 5.5,
        yearFrom: 2017,
        yearTo: null,
      },
      {
        name: 'T3 163 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1477,
        powerHp: 163,
        torqueNm: 265,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.7,
        topSpeedKmh: 195,
        fuelConsumptionCombined: 6.2,
        yearFrom: 2017,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Awarie systemu multimedialnego',
        description: 'Sporadyczne zawieszanie się ekranu dotykowego Sensus.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Osad w EGR/DPF',
        description: 'Typowe dla dieslowskiej wersji przy jeździe miejskiej.',
        severity: 'minor',
        mileageHint: null,
        engineName: 'D4 190 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobrze oceniana pod względem designu i bezpieczeństwa, popularny wybór wśród młodszych nabywców.',
      },
      {
        kind: 'ownership_cost',
        body: 'Koszt zbliżony do XC60, korzystny stosunek wyposażenia do ceny w tej klasie.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź działanie systemu multimedialnego Sensus przed zakupem.',
      },
    ],
  },
  {
    make: 'Opel',
    model: 'Corsa',
    generation: 'F',
    yearFrom: 2019,
    yearTo: null,
    bodyTypes: ['hatchback'],
    summary:
      'Szósta generacja Corsy, zbudowana na platformie PSA (współdzielonej z Peugeot 208) po ' +
      'przejęciu Opla przez PSA/Stellantis.',
    source: 'manual',
    engines: [
      {
        name: '1.2 Turbo 100 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1199,
        powerHp: 100,
        torqueNm: 205,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.0,
        topSpeedKmh: 190,
        fuelConsumptionCombined: 5.2,
        yearFrom: 2019,
        yearTo: null,
      },
      {
        name: '1.5 Diesel 102 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1499,
        powerHp: 102,
        torqueNm: 250,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.7,
        topSpeedKmh: 189,
        fuelConsumptionCombined: 3.8,
        yearFrom: 2019,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Krótka historia rynkowa',
        description: 'Jeszcze niewiele długoterminowych danych o usterkach - model wciąż stosunkowo nowy.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Inna filozofia niż starsze Corsy - zbudowana na platformie PSA po przejęciu Opla przez Stellantis.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niski koszt zakupu i eksploatacji, dobra dostępność części dzięki wspólnej platformie z Peugeot/Citroën.',
      },
      {
        kind: 'buying_advice',
        body: 'Model wciąż stosunkowo nowy na rynku wtórnym - mniej danych o długoterminowej trwałości niż starsze generacje.',
      },
    ],
  },
  {
    make: 'Mercedes-Benz',
    model: 'E-Class',
    generation: 'W213',
    yearFrom: 2016,
    yearTo: null,
    bodyTypes: ['sedan', 'wagon'],
    summary:
      'Piąta generacja Klasy E - bardzo wysoko oceniany komfort i technologia, flagowy przykład klasy ' +
      'biznesowej Mercedesa.',
    source: 'manual',
    engines: [
      {
        name: 'E220d 194 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1950,
        powerHp: 194,
        torqueNm: 400,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 7.3,
        topSpeedKmh: 240,
        fuelConsumptionCombined: 4.6,
        yearFrom: 2016,
        yearTo: null,
      },
      {
        name: 'E200 184 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1991,
        powerHp: 184,
        torqueNm: 300,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 7.7,
        topSpeedKmh: 237,
        fuelConsumptionCombined: 6.5,
        yearFrom: 2016,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Zawieszenie pneumatyczne Airmatic',
        description: 'Awarie opcjonalnego zawieszenia pneumatycznego - kosztowna naprawa.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Kalibracja czujników wspomagania kierowcy',
        description: 'Czujniki radarowe wymagają kalibracji po naprawach blacharskich/szyby.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo wysoko oceniany komfort i technologia, flagowy przykład klasy biznesowej Mercedesa.',
      },
      {
        kind: 'ownership_cost',
        body: 'Wysoki koszt serwisu i części typowy dla segmentu premium D, szczególnie przy zawieszeniu pneumatycznym.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź stan zawieszenia pneumatycznego (jeśli występuje) - to najdroższy potencjalny punkt awarii.',
      },
    ],
  },
  {
    make: 'Kia',
    model: 'Ceed',
    generation: 'III',
    yearFrom: 2018,
    yearTo: null,
    bodyTypes: ['hatchback', 'wagon'],
    summary:
      'Trzecia generacja Ceed - dobra jakość wykonania wspierana 7-letnią gwarancją Kia, konkurencyjny ' +
      'wybór wobec Golfa/Octavii.',
    source: 'manual',
    engines: [
      {
        name: '1.6 CRDi 136 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 1598,
        powerHp: 136,
        torqueNm: 280,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.1,
        topSpeedKmh: 190,
        fuelConsumptionCombined: 4.2,
        yearFrom: 2018,
        yearTo: null,
      },
      {
        name: '1.0 T-GDI 120 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 998,
        powerHp: 120,
        torqueNm: 172,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 10.4,
        topSpeedKmh: 188,
        fuelConsumptionCombined: 5.4,
        yearFrom: 2018,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Osad w EGR/DPF',
        description: 'Zapychanie układu oczyszczania spalin przy dieslu i jeździe miejskiej.',
        severity: 'minor',
        mileageHint: null,
        engineName: '1.6 CRDi 136 KM',
      },
      {
        title: 'Dwumasowe koło zamachowe',
        description: 'Szybsze zużycie przy silnikach diesla.',
        severity: 'minor',
        mileageHint: null,
        engineName: '1.6 CRDi 136 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Dobra jakość wykonania wspierana 7-letnią gwarancją Kia, konkurencyjny wybór wobec Golfa/Octavii.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niższy koszt zakupu niż odpowiedniki VAG, dobra dostępność części.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź czy gwarancja producenta nadal obowiązuje - realnie obniża ryzyko zakupu młodszego egzemplarza.',
      },
    ],
  },
  {
    make: 'Mazda',
    model: 'CX-5',
    generation: 'II',
    yearFrom: 2017,
    yearTo: null,
    bodyTypes: ['suv'],
    summary:
      'Druga generacja CX-5 - bardzo dobrze oceniane prowadzenie jak na SUV-a, wysoka jakość wnętrza w ' +
      'wyższych wersjach.',
    source: 'manual',
    engines: [
      {
        name: '2.2 SkyActiv-D 150 KM',
        engineCode: null,
        fuelType: 'diesel',
        displacementCm3: 2191,
        powerHp: 150,
        torqueNm: 380,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.9,
        topSpeedKmh: 199,
        fuelConsumptionCombined: 4.9,
        yearFrom: 2017,
        yearTo: null,
      },
      {
        name: '2.0 SkyActiv-G 165 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1998,
        powerHp: 165,
        torqueNm: 213,
        gearbox: 'manual',
        driveType: 'fwd',
        acceleration0To100: 9.9,
        topSpeedKmh: 195,
        fuelConsumptionCombined: 6.9,
        yearFrom: 2017,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Korozja progów i krawędzi drzwi',
        description: 'Podobnie jak Mazda 3 z tego okresu - podatność na korozję w newralgicznych punktach.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Osad w EGR/DPF',
        description: 'Typowe dla dieslowskiej wersji przy jeździe miejskiej.',
        severity: 'minor',
        mileageHint: null,
        engineName: '2.2 SkyActiv-D 150 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobrze oceniane prowadzenie jak na SUV-a, wysoka jakość wnętrza w wyższych wersjach.',
      },
      {
        kind: 'ownership_cost',
        body: 'Umiarkowany koszt serwisu, niezależne warsztaty dobrze radzą sobie z Mazdami.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź stan progów i nadkoli pod kątem korozji, szczególnie u egzemplarzy z wilgotnych regionów.',
      },
    ],
  },

  /* ------------------------- reszta gamy Lexusa ------------------------- */

  {
    make: 'Lexus',
    model: 'CT',
    generation: 'CT200h',
    yearFrom: 2010,
    yearTo: 2018,
    bodyTypes: ['hatchback'],
    summary:
      'Kompaktowy hatchback - najbardziej przystępny cenowo model Lexusa, dzielił płytę z Toyotą ' +
      'Auris/Prius. Napęd wyłącznie hybrydowy.',
    source: 'manual',
    engines: [
      {
        name: '200h 136 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 1798,
        powerHp: 136,
        torqueNm: 142,
        gearbox: 'automatic',
        driveType: 'fwd',
        acceleration0To100: 10.3,
        topSpeedKmh: 170,
        fuelConsumptionCombined: 3.8,
        yearFrom: 2010,
        yearTo: 2018,
      },
    ],
    knownIssues: [
      {
        title: 'Ograniczona przestrzeń bagażowa',
        description: 'Bateria hybrydowa zajmuje część przestrzeni bagażnika - charakter konstrukcji, nie usterka.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Twarde zawieszenie w wersji F Sport',
        description: 'Kwestia komfortu jazdy w wersji sportowej, nie awaria.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo niezawodny napęd hybrydowy (sprawdzony w Toyocie Prius/Auris), ale mało przestrzenne wnętrze jak na segment.',
      },
      {
        kind: 'ownership_cost',
        body: 'Bardzo niskie spalanie w mieście, ale wyższa cena serwisu u dealera niż porównywalna Toyota.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź stan baterii trakcyjnej mimo ogólnie dobrej reputacji trwałości hybryd Toyoty/Lexusa.',
      },
    ],
  },
  {
    make: 'Lexus',
    model: 'IS',
    generation: 'XE30',
    yearFrom: 2013,
    yearTo: 2020,
    bodyTypes: ['sedan'],
    summary:
      'Trzecia generacja IS - kompaktowy sedan sportowy, alternatywa dla BMW serii 3/Audi A4 z ' +
      'napędem na tylną oś i opcją hybrydową.',
    source: 'manual',
    engines: [
      {
        name: 'IS300h 223 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 2494,
        powerHp: 223,
        torqueNm: 221,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 8.3,
        topSpeedKmh: 200,
        fuelConsumptionCombined: 4.4,
        yearFrom: 2013,
        yearTo: 2020,
      },
      {
        name: 'IS200t 245 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1998,
        powerHp: 245,
        torqueNm: 350,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 7.0,
        topSpeedKmh: 230,
        fuelConsumptionCombined: 7.7,
        yearFrom: 2015,
        yearTo: 2020,
      },
    ],
    knownIssues: [
      {
        title: 'Ciasne tylne siedzenia',
        description: 'Mniej przestrzeni z tyłu niż w niemieckiej konkurencji segmentu D - kwestia konstrukcji.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Usterki elektryki wnętrza',
        description: 'Sporadyczne problemy z modułami komfortu w starszych egzemplarzach.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobra niezawodność, ale mniej przestronna niż niemiecka konkurencja segmentu D.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niskie koszty serwisu jak na segment premium, IS300h oszczędny w jeździe miejskiej.',
      },
      {
        kind: 'buying_advice',
        body: 'IS300h lepszy wybór do miasta, IS200t do jazdy w trasie i dla lubiących osiągi.',
      },
    ],
  },
  {
    make: 'Lexus',
    model: 'ES',
    generation: 'VII',
    yearFrom: 2018,
    yearTo: null,
    bodyTypes: ['sedan'],
    summary:
      'Siódma generacja ES - pierwsza oficjalnie dostępna w Europie, komfortowy sedan segmentu D/E z ' +
      'napędem wyłącznie hybrydowym na rynku europejskim.',
    source: 'manual',
    engines: [
      {
        name: 'ES300h 218 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 2487,
        powerHp: 218,
        torqueNm: 221,
        gearbox: 'automatic',
        driveType: 'fwd',
        acceleration0To100: 8.9,
        topSpeedKmh: 180,
        fuelConsumptionCombined: 4.7,
        yearFrom: 2018,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Sporadyczne usterki',
        description: 'Praktycznie brak zgłaszanych poważnych usterek - typowe dla Lexusa.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo komfortowa, cicha jazda, ceniona za niezawodność napędu hybrydowego.',
      },
      {
        kind: 'ownership_cost',
        body: 'Niższe spalanie niż konkurencja spalinowa w segmencie D/E premium.',
      },
      {
        kind: 'buying_advice',
        body: 'Dobry wybór zamiast niemieckiej limuzyny tej klasy, jeśli priorytetem jest bezawaryjność.',
      },
    ],
  },
  {
    make: 'Lexus',
    model: 'GS',
    generation: 'IV',
    yearFrom: 2011,
    yearTo: 2020,
    bodyTypes: ['sedan'],
    summary:
      'Czwarta, ostatnia generacja GS przed wycofaniem modelu - sedan segmentu E, alternatywa dla ' +
      'klasy E i serii 5, mniej rozpoznawalna, ale bardzo solidna.',
    source: 'manual',
    engines: [
      {
        name: 'GS300h 223 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 2493,
        powerHp: 223,
        torqueNm: 221,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 9.2,
        topSpeedKmh: 190,
        fuelConsumptionCombined: 4.7,
        yearFrom: 2013,
        yearTo: 2020,
      },
      {
        name: 'GS450h 345 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 3456,
        powerHp: 345,
        torqueNm: 349,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 5.9,
        topSpeedKmh: 250,
        fuelConsumptionCombined: 5.9,
        yearFrom: 2011,
        yearTo: 2020,
      },
    ],
    knownIssues: [
      {
        title: 'Ograniczona dostępność części',
        description: 'Niezależne serwisy w Polsce rzadziej mają na stanie części do Lexusa niż do marek niemieckich.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Koszt ogumienia (F Sport)',
        description: 'Duże koła w wersji F Sport podnoszą koszt wymiany opon.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo solidna alternatywa dla klasy E/serii 5, ale mniej rozpoznawalna marka na rynku wtórnym.',
      },
      {
        kind: 'ownership_cost',
        body: 'Dobra trwałość, ale rzadszy serwis niezależny może wydłużać czas napraw.',
      },
      {
        kind: 'buying_advice',
        body: 'Świetny stosunek jakości do ceny na rynku wtórnym właśnie ze względu na słabszą rozpoznawalność marki.',
      },
    ],
  },
  {
    make: 'Lexus',
    model: 'RC',
    generation: 'I',
    yearFrom: 2014,
    yearTo: null,
    bodyTypes: ['coupe'],
    summary:
      'Stylowe coupe segmentu premium, dzielące płytę z IS. Dostępne od hybrydowego RC300h po ' +
      'napędzane wolnossącym V8 RC F.',
    source: 'manual',
    engines: [
      {
        name: 'RC300h 223 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 2493,
        powerHp: 223,
        torqueNm: 221,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 8.6,
        topSpeedKmh: 190,
        fuelConsumptionCombined: 4.9,
        yearFrom: 2014,
        yearTo: null,
      },
      {
        name: 'RC F 477 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 4969,
        powerHp: 477,
        torqueNm: 530,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 4.5,
        topSpeedKmh: 270,
        fuelConsumptionCombined: 11.3,
        yearFrom: 2014,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Ograniczona widoczność do tyłu',
        description: 'Charakterystyczne dla nadwozia coupe - wąska szyba tylna.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Wysokie spalanie (RC F)',
        description: 'Wolnossący silnik V8 bez turbodoładowania generuje wysokie spalanie w codziennej jeździe.',
        severity: 'minor',
        mileageHint: null,
        engineName: 'RC F 477 KM',
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Stylowe coupe, RC F ceniony za dźwięk wolnossącego V8 w czasach powszechnego downsizingu.',
      },
      {
        kind: 'ownership_cost',
        body: 'RC300h ekonomiczny w codziennej eksploatacji, RC F kosztowny (paliwo, opony, hamulce).',
      },
      {
        kind: 'buying_advice',
        body: 'RC F to auto na wyjątkowe okazje, nie codzienny dojazd - policz realne koszty paliwa przed zakupem.',
      },
    ],
  },
  {
    make: 'Lexus',
    model: 'NX',
    generation: 'I',
    yearFrom: 2014,
    yearTo: 2021,
    bodyTypes: ['suv'],
    summary:
      'Pierwszy kompaktowy SUV Lexusa - wyróżniający się, kanciasty design, bardzo dobrze przyjęty na ' +
      'rynku, głównie sprzedawany z napędem hybrydowym.',
    source: 'manual',
    engines: [
      {
        name: 'NX300h 197 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 2494,
        powerHp: 197,
        torqueNm: 210,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 9.2,
        topSpeedKmh: 180,
        fuelConsumptionCombined: 5.1,
        yearFrom: 2014,
        yearTo: 2021,
      },
      {
        name: 'NX300 235 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 1998,
        powerHp: 235,
        torqueNm: 350,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 7.1,
        topSpeedKmh: 200,
        fuelConsumptionCombined: 8.1,
        yearFrom: 2017,
        yearTo: 2021,
      },
    ],
    knownIssues: [
      {
        title: 'Twarde zawieszenie (F Sport)',
        description: 'Sportowo dostrojone zawieszenie w wersji F Sport kosztem komfortu.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Ograniczona widoczność do tyłu',
        description: 'Wąskie okno bagażnika utrudnia parkowanie bez czujników/kamery.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Bardzo dobrze przyjęty pierwszy kompaktowy SUV Lexusa, wyróżniający się design.',
      },
      {
        kind: 'ownership_cost',
        body: 'NX300h bardzo oszczędny w mieście, wysoka wartość rezydualna na rynku wtórnym.',
      },
      {
        kind: 'buying_advice',
        body: 'Hybrydowy NX300h zdecydowanie bardziej opłacalny przy przewadze jazdy miejskiej.',
      },
    ],
  },
  {
    make: 'Lexus',
    model: 'UX',
    generation: 'I',
    yearFrom: 2018,
    yearTo: null,
    bodyTypes: ['suv'],
    summary:
      'Najmniejszy i najbardziej miejski SUV/crossover Lexusa, zbudowany na platformie TNGA dzielonej ' +
      'z Toyotą C-HR/Corollą. Napęd wyłącznie hybrydowy.',
    source: 'manual',
    engines: [
      {
        name: 'UX250h 184 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 1987,
        powerHp: 184,
        torqueNm: 190,
        gearbox: 'automatic',
        driveType: 'awd',
        acceleration0To100: 8.5,
        topSpeedKmh: 170,
        fuelConsumptionCombined: 4.5,
        yearFrom: 2018,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Ciasne wnętrze i mały bagażnik',
        description: 'Mniejsza przestrzeń użytkowa niż konkurencja segmentu - kompromis wynikający z rozmiaru.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Twarde zawieszenie (F Sport)',
        description: 'Sportowo dostrojone zawieszenie w wersji F Sport kosztem komfortu.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Najmniejszy i najbardziej miejski SUV Lexusa, bardzo oszczędny w eksploatacji.',
      },
      {
        kind: 'ownership_cost',
        body: 'Jeden z najtańszych w eksploatacji SUV-ów premium dzięki napędowi hybrydowemu.',
      },
      {
        kind: 'buying_advice',
        body: 'Sprawdź czy przestrzeń bagażowa wystarcza na Twoje potrzeby - to główny kompromis tego modelu.',
      },
    ],
  },
  {
    make: 'Lexus',
    model: 'LS',
    generation: 'V',
    yearFrom: 2017,
    yearTo: null,
    bodyTypes: ['sedan'],
    summary:
      'Piąta generacja LS - flagowy sedan Lexusa, konkurent serii 7 BMW i klasy S Mercedesa, napęd ' +
      'wyłącznie hybrydowy w Europie.',
    source: 'manual',
    engines: [
      {
        name: 'LS500h 359 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 3456,
        powerHp: 359,
        torqueNm: 348,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 5.5,
        topSpeedKmh: 250,
        fuelConsumptionCombined: 6.6,
        yearFrom: 2017,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Wysoki koszt serwisu',
        description: 'Części i przeglądy kosztowne jak na flagowy model segmentu luksusowego.',
        severity: 'moderate',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'System multimedialny (touchpad)',
        description: 'Sterowanie touchpadem krytykowane przez użytkowników za mniejszą intuicyjność niż pokrętło konkurencji.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Flagowy sedan Lexusa, konkuruje z serią 7 i klasą S, ceniony za komfort i ciszę w kabinie.',
      },
      {
        kind: 'ownership_cost',
        body: 'Bardzo wysoki koszt serwisu i części typowy dla segmentu flagowego premium.',
      },
      {
        kind: 'buying_advice',
        body: 'Mniej rozpoznawalna niż niemiecka konkurencja - zwykle niższa cena na rynku wtórnym przy podobnym poziomie luksusu.',
      },
    ],
  },
  {
    make: 'Lexus',
    model: 'LC',
    generation: 'I',
    yearFrom: 2017,
    yearTo: null,
    bodyTypes: ['coupe', 'convertible'],
    summary:
      'Halo model marki - luksusowe coupe/kabriolet GT, jedno z najbardziej stylowych aut na rynku, ' +
      'dostępne z hybrydowym V6 lub wolnossącym V8.',
    source: 'manual',
    engines: [
      {
        name: 'LC500h 359 KM',
        engineCode: null,
        fuelType: 'hybrid',
        displacementCm3: 3456,
        powerHp: 359,
        torqueNm: 348,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 5.0,
        topSpeedKmh: 250,
        fuelConsumptionCombined: 6.5,
        yearFrom: 2017,
        yearTo: null,
      },
      {
        name: 'LC500 477 KM',
        engineCode: null,
        fuelType: 'petrol',
        displacementCm3: 4969,
        powerHp: 477,
        torqueNm: 540,
        gearbox: 'automatic',
        driveType: 'rwd',
        acceleration0To100: 4.7,
        topSpeedKmh: 270,
        fuelConsumptionCombined: 11.6,
        yearFrom: 2017,
        yearTo: null,
      },
    ],
    knownIssues: [
      {
        title: 'Bardzo ograniczona praktyczność',
        description: 'Nadwozie 2+2 z małym bagażnikiem - charakter auta, nie usterka.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
      {
        title: 'Wysoki koszt ogumienia i hamulców',
        description: 'Duże, szerokie koła i mocne hamulce podnoszą koszt eksploatacji.',
        severity: 'minor',
        mileageHint: null,
        engineName: null,
      },
    ],
    notes: [
      {
        kind: 'reputation',
        body: 'Halo model marki, jedno z najładniejszych coupe na rynku, bardzo wysoko oceniana jakość wykonania.',
      },
      {
        kind: 'ownership_cost',
        body: 'Wysoki koszt eksploatacji typowy dla luksusowego GT - paliwo, opony, przeglądy.',
      },
      {
        kind: 'buying_advice',
        body: 'Kupowane emocjonalnie, nie praktycznie - mimo dobrej reputacji Lexusa sprawdź historię serwisową.',
      },
    ],
  },
];

async function run() {
  let created = 0;
  for (const payload of MODELS) {
    await upsertModel(payload);
    created += 1;
    logger.info(
      { make: payload.make, model: payload.model, generation: payload.generation },
      'Knowledge seed: zapisano',
    );
  }
  logger.info({ models: created }, 'Knowledge seed: gotowe');
}

try {
  await run();
  await pool.end();
  process.exit(0);
} catch (err) {
  logger.error({ err }, 'Knowledge seed nie powiódł się');
  await pool.end();
  process.exit(1);
}
